# --- database schema

# --- !Ups

USE adwdoc;

delete
from agg_params;

INSERT INTO `agg_params` (`param_key`, `aggr_type`, `path`, `is_array`, `data_ref`, `value_list`, `id`)
VALUES ('type', 'simple', '', 0, 'type', 'incident_type', 1),
       ('institution', 'string', 'metadata', 0, 'institution', '', 2),
       ('contact_by', 'simple', 'generaldata', 0, 'contact_by', 'contact_by', 3),
       ('first_contact_date', 'date', 'generaldata', 0, 'first_contact_date', '', 4),
       ('advise_language', 'simple', 'generaldata', 0, 'advise_language', 'advise_language', 5),
       ('become_aware_of', 'simple', 'generaldata', 0, 'become_aware_of', 'become_aware_of', 6),
       ('affected_group', 'simple', 'affected_person', 0, 'affected_group', 'affected_group', 7),
       ('gender', 'simple', 'affected_person', 0, 'gender', 'gender', 8),
       ('age', 'simple', 'affected_person', 0, 'age', 'age', 9),
       ('funding_letigation_costs', 'simple', 'affected_person', 0, 'funding_letigation_costs',
        'funding_letigation_costs', 10),
       ('incident_district', 'simple', 'short_description.incident_place', 0, 'incident_district', 'district', 11),
       ('area_of_discrimination', 'simple', 'incident_typology.general', 0, 'area_of_discrimination',
        'area_of_discrimination ', 12),
       ('form_of_discrimination', 'simple', 'incident_typology.general', 0, 'form_of_discrimination',
        'form_of_discrimination', 13),
       ('causer_company_institution_name', 'string', 'causer_list', 1, 'company_institution_name', '', 14),
       ('causer_type', 'simple', 'incident_typology.causer_typology', 1, 'causer_type', 'causer', 15),
       ('causer_owner_agency', 'simple', 'incident_typology.causer_typology', 1, 'owner_agency', 'owner_agency', 16),
       ('causer_number_of_appartments', 'simple', 'incident_typology.causer_typology', 1, 'number_of_appartments',
        'number_of_appartments', 17),
       ('incident_date', 'date', 'short_description', 0, 'incident_date', '', 18),
       ('involved_list_not_empty', 'count_not_empty', 'involved_list', 1, '', '', 19),
       ('evidence_list_not_empty', 'count_not_empty', 'evidence_list', 1, '', '', 20),
       ('goal_person_concerned', 'simple', 'process_blog_part1', 0, 'goal_person_concerned', 'goal_person_concerned ',
        21),
       ('areas_of_law', 'simple', 'process_blog_part2', 0, 'areas_of_law', 'areas_of_law', 22),
       ('result', 'simple', 'completion', 0, 'result', 'outcome', 23),
       ('support_format', 'simple', 'supporter_list', 1, 'support_format', 'support_format', 24),
       ('form_of_intervention', 'simple', 'interventions', 1, 'form_of_intervention', 'form_of_intervention', 25),
       ('grounds_of_discrimination', 'hierarchical', 'incident_typology.grounds_of_discrimination', 1,
        'selected_grounds', 'grounds_of_discrimination', 26),
       ('grounds_of_discrimination_kat', 'hierarchical_join_kat', 'incident_typology.grounds_of_discrimination', 1,
        'selected_grounds', 'grounds_of_discrimination', 27);

delete
from aggs;

INSERT INTO `aggs` (`id`, `aggr_id`, `param_key1`, `param_key2`, `order`, `title`, `sub_title`, `description`,
                    `population_type`)
VALUES (1, 'agg_type', 'type', '', 20, 'Vorgangstyp', 'Welcher Typ der Beratung kommt am häufigsten vor?', '', 'AMF'),
       (2, 'agg_institution', 'institution', '', 10, 'Träger / Institution',
        'Wie viele Fälle hat welche Institution eingetragen?', '', 'AMF'),
       (3, 'agg_contact_by', 'contact_by', '', 30, 'Kontaktaufnahme durch', 'Wer kommt in die Beratung?', '', 'AMF'),
       (4, 'agg_first_contact_date', 'first_contact_date', '', 31, 'Datum Kontaktaufnahme:',
        'Datum der ersten Kontaktaufnahme?', '', 'AMF'),
       (5, 'agg_advise_language', 'advise_language', '', 32, 'Sprache', 'Sprache in der die Beratung stattfinden soll:',
        '', 'AMF'),
       (6, 'agg_become_aware_of', 'become_aware_of', '', 33, 'Wie haben Sie von der Fachstelle erfahren?',
        'Wie haben Sie von der Fachstelle erfahren?', '', 'AMF'),
       (7, 'agg_affected_group', 'affected_group', '', 34, 'Wer ist betroffen?', 'Wer ist betroffen?', '', 'AMF'),
       (8, 'agg_gender', 'gender', '', 40, 'Gender', 'Wer kommt in die Beratung?', '', 'AMF'),
       (9, 'agg_age', 'age', '', 50, 'Alter', 'Wer kommt in die Beratung?', '', 'AMF'),
       (10, 'agg_funding_letigation_costs', 'funding_letigation_costs', '', 60, 'Prozesskostenübernahme',
        'Sind Prozesskostenübernahmen wahrscheinlich?', '', 'AMF'),
       (11, 'agg_incident_district', 'incident_district', '', 122, 'Bezirk des Vorfalls',
        'In welchen Berliner Bezirken werden die meisten Diskriminierungsvorfälle gemeldet?', '', 'AMF'),
       (12, 'agg_area_of_discrimination', 'area_of_discrimination', '', 80, 'Bereich der Diskriminierung',
        'In welchem Bereich werden die meisten Vorfälle benannt?', '', 'AMF'),
       (13, 'agg_form_of_discrimination', 'form_of_discrimination', '', 90, 'Form der Diskriminierung',
        'Welche Form haben die Diskriminierungsvorfälle?', '', 'AMF'),
       (14, 'agg_causer_company_institution_name', 'causer_company_institution_name', '', 101,
        'Firma/ Institution (Verursacher)', 'Name des Verursachers', '', 'AMF'),
       (15, 'agg_causer_type', 'causer_type', '', 100, 'Typ der Verursachenden', 'Wer diskriminiert?', '', 'AMF'),
       (16, 'agg_causer_owner_agency', 'causer_owner_agency', '', 110, 'bei Wohnunseigentümer*in / -verwalter*in',
        '\"Welche \"\"Geschäftsform\"\" hat der Verursacher?\"', '', 'AMF'),
       (17, 'agg_causer_number_of_appartments', 'causer_number_of_appartments', '', 120,
        'bei Wohnunseigentümer*in / -verwalter*in', 'Wie viele Wohnungen hat der Verursachungstyp', '', 'AMF'),
       (18, 'agg_incident_date', 'incident_date', '', 121, 'Datum des Vorfalls',
        'Wann hat die Diskriminierung stattgefunden?', '', 'AMF'),
       (19, 'agg_involved_list_not_empty', 'involved_list_not_empty', '', 125, 'Zeug*innen', 'Gibt es Zeug*innen?', '',
        'AMF'),
       (20, 'agg_evidence_list_not_empty', 'evidence_list_not_empty', '', 127, 'Beweise', 'Wurden Beweise gesammelt?',
        '', 'AMF'),
       (21, 'agg_goal_person_concerned', 'goal_person_concerned', '', 130, 'Ziel(e) der betroffenen Person',
        'Was sind die Erwartungen und Ziele der betroffenen Person', '', 'AMF'),
       (22, 'agg_areas_of_law', 'areas_of_law', '', 140, 'Relevante(r) Rechtsbereich(e)',
        'Welche Rechtsbereiche sind betroffen', '', 'AMF'),
       (23, 'agg_result', 'result', '', 150, 'Abschluss / Ergebnis',
        'Welche Ergebnisse konnte die Fachstelle erzielen?', '', 'AMF'),
       (24, 'agg_support_format', 'support_format', '', 61, 'Unterstützungsformat',
        'Welche Form der Unterstützung kommt am häufigsten vor?', '', 'AMF'),
       (25, 'agg_form_of_intervention', 'form_of_intervention', '', 145, 'Interventionen der Fachstelle',
        'Welche Intervention hat die Fachstelle durchgeführt?', '', 'AMF'),
       (26, 'agg_grounds_of_discrimination', 'grounds_of_discrimination', '', 62, 'Diskriminierungsmerkmal',
        'Aufgrund von welchen (zugeschriebenen) Merkmalen wurden die betroffenen Personen diskriminiert?', '', 'AMF'),
       (27, 'agg_type_contact_by', 'type', 'contact_by', 300, 'Vorgangstyp pro Kontaktaufnahme durch', '', '', 'AMF'),
       (28, 'agg_contact_by_gender', 'contact_by', 'gender', 310, 'Kontaktaufnahme durch pro Geschlecht', '', '',
        'AMF'),
       (29, 'agg_contact_by_age', 'contact_by', 'age', 320, 'Kontaktaufnahme durch pro Alter', '', '', 'AMF'),
       (30, 'agg_gender_incident_district', 'gender', 'incident_district', 330, 'Gender pro Bezirk des Vorfalls', '',
        '', 'AMF'),
       (31, 'agg_area_of_discrimination_incident_district', 'area_of_discrimination', 'incident_district', 340,
        'Bereich der Diskriminierung pro Bezirk des Vorfalls', '', '', 'AMF'),
       (32, 'agg_form_of_discrimination_incident_district', 'form_of_discrimination', 'incident_district', 350,
        'Form der Diskriminierung pro Bezirk des Vorfalls', '', '', 'AMF'),
       (33, 'agg_form_of_discrimination_area_of_discrimination', 'form_of_discrimination', 'area_of_discrimination',
        360, 'Form der Diskriminierung pro Bereich der Diskriminierung', '', '', 'AMF'),
       (34, 'agg_causer_type_grounds_of_discrimination_kat', 'causer_type', 'grounds_of_discrimination_kat', 370,
        'Typ des Verursachers pro Diskriminerungsmerkmal', '', '', 'AMF'),
       (35, 'agg_causer_type_area_of_discrimination', 'causer_type', 'area_of_discrimination', 380,
        'Typ des Verursachers pro Bereich der Diskriminierung', '', '', 'AMF'),
       (36, 'agg_causer_type_form_of_discrimination', 'causer_type', 'form_of_discrimination', 390,
        'Typ des Verursachers pro Form der Diskriminierung', '', '', 'AMF'),
       (37, 'agg_causer_type_gender', 'causer_type', 'gender', 400, 'Typ des Verursachers pro Geschlecht', '', '',
        'AMF'),
       (38, 'agg_causer_type_age', 'causer_type', 'age', 410, 'Typ des Verursachers pro Alter', '', '', 'AMF'),
       (39, 'agg_grounds_of_discrimination_kat_gender', 'grounds_of_discrimination_kat', 'gender', 420,
        'Diskriminierungsmerkmal pro Gender', '', '', 'AMF'),
       (40, 'agg_grounds_of_discrimination_kat_age', 'grounds_of_discrimination_kat', 'age', 430,
        'Diskriminierungsmerkmal pro Alter', '', '', 'AMF'),
       (41, 'agg_goal_person_concerned_age', 'goal_person_concerned', 'age', 440,
        'Ziel der betroffenen Person pro Alter', '', '', 'AMF'),
       (42, 'agg_goal_person_concerned_gender', 'goal_person_concerned', 'gender', 450,
        'Ziel der betroffenen Person pro Geschlecht', '', '', 'AMF'),
       (43, 'agg_goal_person_concerned_form_of_intervention', 'goal_person_concerned', 'form_of_intervention', 460,
        'Ziel der betroffenen Person pro Form der Intervention', '', '', 'AMF'),
       (44, 'agg_goal_person_concerned_result', 'goal_person_concerned', 'result', 470,
        'Ziel der betroffenen Person pro Abschluss Ergebnis', '', '', 'AMF'),
       (45, 'agg_area_of_discrimination_form_of_intervention', 'area_of_discrimination', 'form_of_intervention', 480,
        'Bereich der Diskriminierung pro Form der Intervention', '', '', 'AMF'),
       (46, 'agg_area_of_discrimination_result', 'area_of_discrimination', 'result', 490,
        'Bereich der Diskriminierung pro Abschluss Ergebnis', '', '', 'AMF'),
       (47, 'agg_causer_type_result', 'causer_type', 'result', 500, 'Typ des Verursachers pro Abschluss Ergebniss', '',
        '', 'AMF'),
       (48, 'agg_incident_district_causer_type', 'incident_district', 'causer_type', 510,
        'Bezirk des Vorfalls + Typ des Verursachers', '', NULL, 'AMF');

# --- !Downs

USE adwdoc;

delete
from agg_params;

delete
from aggs;
